### ISSUE TITLE
So Listen, Summer 2023 Checklist

### ISSUE THREAD

**Issue by lancealanmartin** [CopticScriptorium/shenoute-canons8-dev#1]
So Listen FL 15-28

- [x] linguistic annotation
- [x] chapter_n based on AB paragraphs
- [x] verse_n/sentence division
- [x] pb_xml_id
- [x] entities
- [x] identities
- [x] indexing and metadata
- [x]  editorial review by @ctschroeder
- [x]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)

## For next release

XO 35-42 (started by @Anri3006; @LCBM0828 will finish)
- [x] linguistic annotation
- [ ] chapter_n based on AB paragraphs
- [ ] verse_n/sentence division
- [ ] pb_xml_id
- [ ] entities
- [ ] identities
- [x] indexing and metadata
- [ ]  editorial review by @ctschroeder
- [ ]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)

**Comment by ctschroeder** [comment]
The metadata is done except for URNS, next/previous/witness (which require URNs), identities, entities. Please assign them back to me in gitdox when you're done with the chapter divisions, and I'll add the URNs.

**Comment by lancealanmartin** [comment]
I went through the segmentation for both So Listen docs. Based on the text, I think they are fragments of My Heart is Crushed and not So Listen. I remember reading this text from Anne Boud'hors edition a few years back. However, Emmel seems to have these folios listed as So Listen. Am I missing something?

The relevant pages in Emmel are 594; 205; 210.

**Comment by ctschroeder** [comment]
I have Anne’s edition at home and will compare and get back to you

Sent from my iPhone

**Comment by lancealanmartin** [comment]
Thanks!

**Comment by ctschroeder** [comment]
FL 15-28 and XO 35-42 are both So Listen. According to both Anne and Stephen, So Listen ends at XO 63.9. My Heart Is Crushed begins on line 10 of XO 63. Maybe you read parts of both So Listen and My Heart is Crushed? (Also Shenoute is quite repetitive in vol 8 of the Canons IIRC.)

**Comment by lancealanmartin** [comment]
Great! Thanks for checking. I think it must be repetition. I have a scanned bit of My Heart is Crushed, and Shenoute uses similar (though not identical) language.

**Comment by ctschroeder** [comment]
I think needs to wait for the next round -- I don't have time for sentence segmentation, etc.

**Comment by LCBM0828** [comment]
I have gone through and added chapter/sentence divisions from AB for FL15-28. Entities and Identities are also done. This should be ready for a metadata review.

**Comment by ctschroeder** [comment]
this is waiting for a few more corrections from LCBM and then will be ready

**Comment by LCBM0828** [comment]
I have just completed the review and correction of all the necessary items on the list. What status should I assign? Do you want it back or should it go directly to Amir?

**Comment by ctschroeder** [comment]
@LCBM0828 I got it thanks

**Comment by ctschroeder** [comment]
this is done
