### ISSUE TITLE
My Heart is Crushed Publication checklist summer 2023

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/shenoute-canons8-dev#2]
- [x] shenoute.crushed.FL83-86
    - [x] linguistic annotation
    - [x] chapter_n
    - [x] verse_n/sentence division
    - [x] pb_xml_id
    - [x] entities
    - [x] identities
    - [x] indexing and metadata
    - [x]  editorial review by @ctschroeder
    - [x]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)

- [x] shenoute.crushed.FL95-96 
    - [x] linguistic annotation
    - [x] chapter_n
    - [x] verse_n/sentence division
    - [x] pb_xml_id
    - [x] entities
    - [x] identities
    - [x] indexing and metadata
    - [x]  editorial review by @ctschroeder
    - [x]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)
    
- [x] shenoute.crushed.FL105-106
    - [x] linguistic annotation
    - [x] chapter_n
    - [x] verse_n/sentence division
    - [x] pb_xml_id
    - [x] entities
    - [x] identities
    - [x] indexing and metadata
    - [x]  editorial review by @ctschroeder
    - [x]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)

## Next time
- [ ] shenoute.crushed.FL125-132
    - [x] linguistic annotation
    - [ ] chapter_n
    - [ ] verse_n/sentence division
    - [x] pb_xml_id
    - [ ] entities
    - [ ] identities
    - [ ] indexing and metadata
    - [ ]  editorial review by @ctschroeder
    - [ ]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)

- [ ] shenoute.crushed.FL133-140
    - [x] linguistic annotation
    - [ ] chapter_n
    - [ ] verse_n/sentence division
    - [x] pb_xml_id
    - [ ] entities
    - [ ] identities
    - [ ] indexing and metadata
    - [ ]  editorial review by @ctschroeder
    - [ ]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)

**Comment by ctschroeder** [comment]
@LCBM0828 Hi Lydia. Do you know what's going on with 95-96? Thanks so much. You can email if you prefer.

**Comment by LCBM0828** [comment]
I was getting commit errors but now it won’t even load without an error. I
am not sure how to proceed. I sent an email with this question this morning
as well if that is easier.

**Comment by ctschroeder** [comment]
Hi I can hop on the zoom early in 4 min and show you. You will need to download the sgml from GitHub and reload it as a new doc

**Comment by LCBM0828** [comment]
Hopping on now!

**Comment by ctschroeder** [comment]
@LCBM0828 will check the spreadsheet today, @ctschroeder will add sentence and chapter breaks, @LCBM0828 will do entities so we can get it to @amir-zeldes by Thursday

**Comment by LCBM0828** [comment]
@ctschroeder finished my review and FL95-96B is now ready for sentence/chap breaks

**Comment by ctschroeder** [comment]
Great! @LCBM0828 FL95-96 is ready for entities and identities. Please assign to Amir to publish when you are done. Please don't change the sentence spans. 
Can you also make sure the metadata for entities and identities is accurate (checked? gold? etc.) before assigning to Amir?
You can comment here when done. Thanks so much!!!

**Comment by ctschroeder** [comment]
(also I deleted the old document and renamed the new one-- the current FL 95-96 is the correct one)

**Comment by LCBM0828** [comment]
@ctschroeder Done. Reviewed the metadata, ran entities and identities, checked, and updated the status for those categories.

**Comment by ctschroeder** [comment]
All set! Thanks!
