### ISSUE TITLE
So Listen Summer/Fall 2024 pub checklist

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/shenoute-canons8-dev#5]
XO 35-42 (started by @Anri3006; @LCBM0828 will finish)
- [x] linguistic annotation
- [ ] chapter_n based on AB paragraphs
- [ ] verse_n/sentence division
- [ ] pb_xml_id
- [ ] entities
- [ ] identities
- [x] indexing and metadata
- [ ]  editorial review by @ctschroeder
- [ ]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)
